name: Build Docker Images
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'apple/**'
      - 'android/**'

permissions:
  packages: write

jobs:
  build-docker-images:
    name: Build docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Login to GitHub container registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the backend docker image
        run: |
          docker build . --file packages/api/Dockerfile --tag "ghcr.io/imtoanle/omnivore-backend:${GITHUB_SHA}" --tag ghcr.io/imtoanle/omnivore-backend:latest
          docker push ghcr.io/imtoanle/omnivore-backend:${GITHUB_SHA}
      - name: Build the db migrate docker image
        run: |
          docker build . --file packages/db/Dockerfile --tag "ghcr.io/imtoanle/omnivore-db:${GITHUB_SHA}" --tag ghcr.io/imtoanle/omnivore-db:latest
          docker push ghcr.io/imtoanle/omnivore-db:${GITHUB_SHA}
      - name: Build the content-fetch docker image
        run: |
          docker build --file packages/content-fetch/Dockerfile . --tag "ghcr.io/imtoanle/omnivore-content-fetch:${GITHUB_SHA}" --tag ghcr.io/imtoanle/omnivore-content-fetch:latest
          docker push ghcr.io/imtoanle/omnivore-content-fetch:${GITHUB_SHA}
